[LCA-3] Testing utils configuration (Jest, RTL, MSW) (#2)
* Implemented: MSW server with default handlers

* Added: Testing configuration set up

* Added: Test run to audit workflow

* Added: Jest config and setup files

* Added: Jest, Testing Library, MSW and more

* Updating tsconfig to include jest.setup.ts and exclude /.next

* Update sonar config

* Modified audit

* Rollback and set GITHUB_TOKEN

* Deleting sonar

diff --git a/.github/workflows/audit.yml b/.github/workflows/audit.yml
--- a/.github/workflows/audit.yml
+++ b/.github/workflows/audit.yml
@@ -42,6 +42,13 @@ jobs:
           npm run lint || (echo "❌ ESLint failed!" && exit 1)
           echo "✅ ESLint passed!"
 
-      # 6. Final message
+      # 6. Run tests
+      - name: 🧪 Run tests
+        run: |
+          echo "🧪 Running tests..."
+          npm run test || (echo "❌ Tests failed!" && exit 1)
+          echo "✅ Tests passed!"
+
+      # 7. Final message
       - name: 🎉 All checks passed!
         run: echo "🚀 ✅ All checks completed successfully!"
